name: Check Lint & Test on Every Push to Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_and_test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/setup@v1
        with:
          version: 11
          runtime: node@24
          cache: true

      - name: Install Dependecies
        run: pnpm install

      - name: Run Lint
        run: pnpm lint

      - name: Run Test
        run: pnpm test







          
